#!/bin/sh

clear

echo "PUT tests"

for file in cb@d cbig csmall cbin c-_-
do
   echo "Processing $file"
   curl -T $file http://localhost:8309/$file
   diff ../$file $file >d_$file
done

echo "HEAD tests"
for file in s_bad s_big s_f@il s_small s_02IbY3tf
do
   echo "Processing $file"
   curl -I http://localhost:8309/$file
done

echo "GET tests"
for file in s_bad s_big s_f@il s_small s_02IbY3tf
do
   echo "Processing $file"
   curl http://localhost:8309/$file --output $file
   diff ../$file $file >d_$file
done
