#!/bin/bash

clear

echo "PUT tests"

for file in {1..6}
do
   echo "PUT $file"
   curl -T $file http://localhost:8080/$file &
   #diff ../$file $file >d_$file
done
wait

for file in {1..6}
do
   echo "GET $file"
   curl http://localhost:8080/c$file --output $file &
done
wait

#for file in csmall cbig
#do
#   echo "PUT $file"
#   time curl -T $file http://localhost:8080/$file
#   #diff ../$file $file >d_$file
#done
#
#echo "HEAD tests"
#for file in s_bad s_f@il s_dne s_big s_small
#do
#   echo "HEAD $file"
#   curl -I http://localhost:8080/$file
#done
#
#echo "GET tests"
#for file in s_bad s_f@il s_dne s_big s_small
#do
#   echo "GET $file"
#   curl http://localhost:8080/$file --output $file
#   diff ../$file $file >d_$file
#done

#echo "health check"
#
#curl http://localhost:8080/healthcheck --output healthcheck
#curl http://localhost:8080/healthcheck --output healthcheck
#curl http://localhost:8080/healthcheck --output healthcheck
#curl http://localhost:8080/healthcheck --output healthcheck
