#!/bin/bash

clear

echo "make testing files"
for file in {1..6}
do
echo "foo bar bim" > $file
done

#echo "PUT tests"
#for file in {1..6}
#do
#   echo "PUT $file"
#   curl -T $file http://localhost:1234/$file
#done
#wait
#
#echo "GET tests"
#for file in {1..6}
#do
#   echo "GET $file"
#   curl http://localhost:1234/c$file --output $file
#done
#wait
#
echo "health check"
curl http://localhost:1234/healthcheck --output healthcheck

echo "remove testing files"
for file in {1..6}
do
rm $file
done
