#!/bin/bash

clear

echo "make testing files"
for file in {1..6}
do
echo "foo bar bim" > $file
done

#echo "PUT small tests"
#for file in {1..6}
#do
#   echo "PUT $file"
#   curl -T $file http://localhost:1234/s$file
#done
#wait
#
#echo "GET small tests"
#for file in {1..6}
#do
#   echo "GET $file"
#   curl http://localhost:1234/s$file --output s$file
#done
#wait

echo "PUT big tests"
for file in {1..2}
do
   echo "PUT b$file"
   curl -T b$file http://localhost:1234/sb$file
done
wait

echo "GET big tests"
for file in {1..2}
do
   echo "GET sb$file"
   curl http://localhost:1234/sb$file --output sb$file
done
wait
#
#echo "PUT binary"
#curl -T WRITEUP.pdf http://localhost:1234/WRITEUP
#
#echo "GET binary"
#curl http://localhost:1234/WRITEUP --output WRITEUP

#echo "health check"
#curl http://localhost:1234/healthcheck --output healthcheck

echo "remove testing files"
for file in {1..6}
do
rm $file
done
